[package]
name = "meetup_client_lib"
version = "0.1.0"
authors = ["Journeyman <antisocial@storiepvtride.it>"]

[dependencies]
log = "0.3.8"
env_logger = "0.4.3"
reqwest = "0.7.3"
serde = "1.0.27"
serde_json = "1.0.9"
serde_derive = "1.0.27"
futures = "0.1.14"
hyper = "0.11.2"
quick-error = "1.2.1"
